package com.zjyz.agent.orch;

public enum AgentIntentType {
    BUSINESS_QUERY,
    PROJECT_LIST,
    PROJECT_RECONCILIATION_DUE,
    PROJECT_CONTRACT_STATUS,
    PROJECT_MATERIAL_OCCUPANCY,
    PROJECT_ACTIVITY,
    PROJECT_SUMMARY,
    INVENTORY_SUMMARY,
    INVENTORY_OPERATIONS,
    INVENTORY_LEDGER_TRACE,
    DOCUMENT_SEARCH,
    DOCUMENT_AUDIT,
    PROJECT_RENT_MATERIALS,
    ENTERPRISE_KNOWLEDGE_UNSUPPORTED,
    UNSUPPORTED_BUSINESS,
    HELP_KNOWLEDGE,
    MATERIAL_ESTIMATE,
    MATERIAL_LIFECYCLE,
    CONTRACT_COMMERCIAL,
    FINANCE_RECEIVABLE_COLLECTION,
    FINANCE_ENTERPRISE_KPI,
    FINANCE_SUPPLIER_PAYABLE_SUMMARY,
    RISK_OWNER_ACTION_CENTER
}
