use zjyz;

CREATE TABLE IF NOT EXISTS agent_knowledge_source (
  source_id VARCHAR(64) NOT NULL COMMENT '知识来源ID',
  scope_type VARCHAR(16) NOT NULL DEFAULT 'TENANT' COMMENT 'PLATFORM/TENANT/PROJECT',
  cid VARCHAR(100) DEFAULT NULL COMMENT '企业ID，平台知识为空',
  project_id VARCHAR(64) DEFAULT NULL COMMENT '项目ID，V1预留',
  source_type VARCHAR(32) NOT NULL COMMENT 'BUILTIN/HELP_ARTICLE/UPLOAD',
  external_ref VARCHAR(128) DEFAULT NULL COMMENT '内置知识或帮助文章引用',
  title VARCHAR(255) NOT NULL COMMENT '知识标题',
  description VARCHAR(1000) DEFAULT NULL COMMENT '知识说明',
  domain_code VARCHAR(32) NOT NULL DEFAULT 'GENERAL' COMMENT '知识领域',
  tags VARCHAR(1000) DEFAULT NULL COMMENT '标签，英文逗号分隔',
  authority_code VARCHAR(32) NOT NULL DEFAULT 'TENANT_APPROVED' COMMENT '知识权威级别',
  version_no INT NOT NULL DEFAULT 1 COMMENT '版本号',
  active_version TINYINT NOT NULL DEFAULT 1 COMMENT '是否当前版本',
  lifecycle_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED/UNPUBLISHED/ARCHIVED',
  index_status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/PROCESSING/READY/FAILED',
  original_file_name VARCHAR(255) DEFAULT NULL COMMENT '原文件名',
  mime_type VARCHAR(128) DEFAULT NULL COMMENT '文件MIME',
  file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件字节数',
  object_key VARCHAR(500) DEFAULT NULL COMMENT 'OSS对象键',
  content_checksum CHAR(64) DEFAULT NULL COMMENT 'SHA-256',
  parser_version VARCHAR(32) DEFAULT NULL COMMENT '解析器版本',
  embedding_model VARCHAR(64) DEFAULT NULL COMMENT '向量模型',
  embedding_dimensions INT DEFAULT NULL COMMENT '向量维度',
  chunk_count INT NOT NULL DEFAULT 0 COMMENT '分段数量',
  error_code VARCHAR(32) DEFAULT NULL COMMENT '安全错误码',
  error_message VARCHAR(1000) DEFAULT NULL COMMENT '安全错误摘要',
  created_by VARCHAR(100) NOT NULL COMMENT '创建用户',
  updated_by VARCHAR(100) NOT NULL COMMENT '最后修改用户',
  published_by VARCHAR(100) DEFAULT NULL COMMENT '发布用户',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  published_at DATETIME DEFAULT NULL COMMENT '发布时间',
  archived_at DATETIME DEFAULT NULL COMMENT '归档时间',
  PRIMARY KEY (source_id),
  KEY idx_agent_knowledge_source_tenant (cid, lifecycle_status, updated_at),
  KEY idx_agent_knowledge_source_external (scope_type, source_type, external_ref),
  KEY idx_agent_knowledge_source_checksum (cid, content_checksum),
  KEY idx_agent_knowledge_source_active (cid, active_version, lifecycle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Agent知识来源及版本';

CREATE TABLE IF NOT EXISTS agent_knowledge_chunk (
  chunk_id VARCHAR(64) NOT NULL COMMENT '知识分段ID',
  source_id VARCHAR(64) NOT NULL COMMENT '知识来源ID',
  source_version INT NOT NULL COMMENT '来源版本',
  cid VARCHAR(100) DEFAULT NULL COMMENT '企业ID',
  chunk_seq INT NOT NULL COMMENT '分段顺序',
  heading_path VARCHAR(1000) DEFAULT NULL COMMENT '标题路径',
  content LONGTEXT NOT NULL COMMENT '分段权威原文',
  content_hash CHAR(64) NOT NULL COMMENT '分段SHA-256',
  token_count INT NOT NULL DEFAULT 0 COMMENT '估算Token数',
  qdrant_collection VARCHAR(128) DEFAULT NULL COMMENT 'Qdrant集合别名',
  qdrant_point_id VARCHAR(64) DEFAULT NULL COMMENT 'Qdrant Point ID',
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/SUPERSEDED/DELETED',
  metadata_json LONGTEXT DEFAULT NULL COMMENT '分段扩展元数据',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (chunk_id),
  UNIQUE KEY uk_agent_knowledge_chunk_seq (source_id, source_version, chunk_seq),
  KEY idx_agent_knowledge_chunk_source (cid, source_id, status),
  KEY idx_agent_knowledge_chunk_point (qdrant_point_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Agent知识分段';

CREATE TABLE IF NOT EXISTS agent_knowledge_ingest_job (
  job_id VARCHAR(64) NOT NULL COMMENT '处理任务ID',
  source_id VARCHAR(64) NOT NULL COMMENT '知识来源ID',
  source_version INT NOT NULL COMMENT '来源版本',
  cid VARCHAR(100) DEFAULT NULL COMMENT '企业ID',
  job_type VARCHAR(16) NOT NULL COMMENT 'INDEX/DELETE/SYNC',
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  attempt_count INT NOT NULL DEFAULT 0 COMMENT '尝试次数',
  next_retry_at DATETIME DEFAULT NULL COMMENT '下次重试时间',
  locked_by VARCHAR(100) DEFAULT NULL COMMENT '处理节点',
  locked_at DATETIME DEFAULT NULL COMMENT '领取时间',
  error_code VARCHAR(32) DEFAULT NULL COMMENT '安全错误码',
  error_message VARCHAR(1000) DEFAULT NULL COMMENT '安全错误摘要',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  started_at DATETIME DEFAULT NULL COMMENT '开始时间',
  completed_at DATETIME DEFAULT NULL COMMENT '完成时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (job_id),
  KEY idx_agent_knowledge_job_queue (status, next_retry_at, created_at),
  KEY idx_agent_knowledge_job_source (source_id, source_version, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Agent知识异步处理任务';

CREATE TABLE IF NOT EXISTS agent_run_knowledge_ref (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  run_id VARCHAR(64) NOT NULL COMMENT 'Agent Run ID',
  message_id VARCHAR(64) DEFAULT NULL COMMENT '最终消息ID',
  cid VARCHAR(100) NOT NULL COMMENT '企业ID',
  source_id VARCHAR(64) NOT NULL COMMENT '知识来源ID',
  source_version INT NOT NULL DEFAULT 1 COMMENT '来源版本',
  chunk_id VARCHAR(64) DEFAULT NULL COMMENT '知识分段ID',
  retrieval_method VARCHAR(16) NOT NULL COMMENT 'STRUCTURED/KEYWORD/VECTOR',
  rank_no INT NOT NULL DEFAULT 0 COMMENT '召回排名',
  raw_score DECIMAL(12,8) DEFAULT NULL COMMENT '原始分数',
  final_score DECIMAL(12,8) DEFAULT NULL COMMENT '合并分数',
  cited TINYINT NOT NULL DEFAULT 1 COMMENT '是否进入最终上下文',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_agent_run_knowledge_ref_run (run_id, rank_no),
  KEY idx_agent_run_knowledge_ref_source (cid, source_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Agent回答知识引用审计';

CREATE TABLE IF NOT EXISTS agent_semantic_definition (
  semantic_id VARCHAR(64) NOT NULL COMMENT '语义定义ID',
  semantic_code VARCHAR(128) NOT NULL COMMENT '稳定语义编码',
  title VARCHAR(255) NOT NULL COMMENT '标题',
  type_code VARCHAR(32) NOT NULL COMMENT '定义类型',
  domain_code VARCHAR(32) NOT NULL DEFAULT 'GENERAL' COMMENT '业务领域',
  authority_code VARCHAR(32) NOT NULL COMMENT '权威来源',
  status VARCHAR(16) NOT NULL DEFAULT 'APPROVED' COMMENT 'DRAFT/APPROVED/ARCHIVED',
  effective_date DATE DEFAULT NULL COMMENT '生效日期',
  expired_date DATE DEFAULT NULL COMMENT '失效日期',
  content LONGTEXT NOT NULL COMMENT '定义正文',
  keywords VARCHAR(2000) DEFAULT NULL COMMENT '关键词',
  tool_hints VARCHAR(2000) DEFAULT NULL COMMENT '建议工具',
  version_no INT NOT NULL DEFAULT 1 COMMENT '版本',
  source_ref VARCHAR(1000) DEFAULT NULL COMMENT '来源引用',
  created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建者',
  approved_by VARCHAR(100) DEFAULT NULL COMMENT '审批者',
  created_at DATETIME NOT NULL COMMENT '创建时间',
  updated_at DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (semantic_id),
  UNIQUE KEY uk_agent_semantic_code_version (semantic_code, version_no),
  KEY idx_agent_semantic_active (status, domain_code, effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Agent动态业务语义定义';
